name: Bug report
description: Report a defect or regression
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please provide enough detail to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and configuration when possible.
      placeholder: |
        1. Configure ...
        2. Start app ...
        3. Trigger unlock ...
        4. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v0.9.0
  - type: input
    id: os
    attributes:
      label: OS and build
      placeholder: Windows 11 23H2
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs from `%LOCALAPPDATA%\LoginShot\logs` and screenshots if available.
